### ISSUE TITLE
Failed to parse config file: invalid character '"' after object key:value pair

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#337]
Hi @or-else,
I updated my tinode docker swarm to latest and it breaks with the following error.
```
2020/01/08 08:15:41 Initializing mysql 110
2020/01/08 08:15:41 Failed to parse config file:invalid character '"' after object key:value pair
```

I started the container manually to try to do more debugging...
```
2020/01/08 08:15:41 Server v0.16:/opt/tinode/tinode:v0.16.3-rc4; db: 'mysql'; pid 44; 2 process(es)
2020/01/08 08:15:41 Using config from '/opt/tinode/working.config'
2020/01/08 08:15:41 Failed to parse config file: invalid character '"' after object key:value pair
```

Any idea why there is an invalid character in the generated config?
Environment configurationen
```
    environment:
#      UPGRADE_DB: 'true'
#      RESET_DB: 'true'
      SMTP_SERVER: smtp.example.com
      SMTP_PORT: '25'
      SMTP_SENDER: noreply@example.com
      SMTP_HOST_URL: https://chat.example.com
      SMTP_PASSWORD: <PW_STRING>
      FCM_CRED_FILE: /path/to/file.json 
      FCM_SENDER_ID: <ID_STRING>
      FCM_VAPID_KEY: <KEY_STRING>
```

Any change to add the line to the error message for future debugging?
