### ISSUE TITLE
CLI Request failed

### ISSUE THREAD

**Issue by kisulken** [tinode/chat#344]
### Subject of the issue
Running `tinode/tinode-rethinkdb:0.16.2` docker container and connecting to it via CLI using `python tn-cli.py --host="0.0.0.0:16061" --no-login`

### Is this a bug report of a feature request?
- [X] Bug report
- [ ] Feature request

#### Server-side
  * platform: Mac OS 10.14.6 + docker 2.1.0.5
  * version of tinode server, e.g. `0.16.2`
  * database backend: rethink db
  
#### Client-side
- [X] tn-cli
  Python 2.7.15
- Version of the client `0.16.2`

### Steps to reproduce
Run docker image
```
  tinode:
    container_name: tinode_messaging
    image: tinode/tinode-rethinkdb:0.16.2
    hostname: tinode
    restart: on-failure:5
    environment:
      GET_HOST_FROM: dns
      EXT_CONFIG: /tinode.conf
    volumes:
      - ../tinodedata/new_tinode.conf:/tinode.conf
      - ../tinodedata/logs:/var/log
    ports:
      - 6060:18080
      - 16061:16061
    depends_on:
      - tinode_db
    networks:
      - lollinet
```

### Expected behaviour
Successful connection to the server

### Actual behaviour
Instead of connecting to the server the error is being printed

### Server-side log
No server side errors

### Client-side log
```
$ python tn-cli.py --host="0.0.0.0:16061" --no-login
Tinode command line client. Version 1.2.1/0.16.2; gRPC/1.26.0.
Server at '0.0.0.0:16061' 
tn> Request failed: coercing to Unicode: need string or buffer, int found
Shutting down...
```
Additional logs after I added some extra print(..)
`<type 'exceptions.TypeError'> tn-cli.py 888`

My goal is to be able to register users at Tinode from Go application. Currently I am doing it by executing python cli script with `.must $user acc --scheme=basic --uname=...`. Is there any other way I could achieve the same result without using python cli script? Is there a Go client for tinode?
