### ISSUE TITLE
tinode-mysql failed attempts to connect as root

### ISSUE THREAD

**Issue by Losmoges** [tinode/chat#469]
### Subject of the issue
Just to be clear, I do not have any issue with running the application. This issue is about the logs.

Errors appear in logs when I want to disallow connecting to mysql as root. I may want to share a database with another application in the future. This seems to work by changing the env var MYSQL_DSN for the docker container. Even though the migration and app itsself seems to be working, something keeps trying to connect to mysql as root.

I have been looking through the code but I can't seem to find the culprit. The mysql adapter class seems to initialize on the proper config according to the logs.

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform: Docker for Windows
  * version of tinode server: tinode/tinode-mysql:0.16.5
  * database backend: mysql

#### Client-side
N/A

### Steps to reproduce
Using docker-compose up

<details>
  <summary>docker-compose.yml</summary>

  ```
version: "3"

networks:
  tinode:

services:
  mysql:
    image: mysql:5.7
    networks:
    - tinode
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 4s
      retries: 12
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: aye
      MYSQL_DATABASE: tinode
      MYSQL_USER: tinode
      MYSQL_PASSWORD: tinode

  tinode:
    depends_on: 
    - mysql
    image: tinode/tinode-mysql:0.16.5
    networks:
    - tinode
    ports:
    - "6060:6060"
    restart: "on-failure"
    environment:
      MYSQL_DSN: tinode:tinode@tcp(mysql)/tinode
  ```
</details>

Validate the working.config in the running container..

```
$ docker exec tinode_tinode_1 grep -A 2 mysql working.config
                "use_adapter": "mysql",
                "adapters": {
                        "mysql": {
                                "database": "tinode",
                                "dsn": "tinode:tinode@tcp(mysql)/tinode?parseTime=true&collation=utf8mb4_unicode_ci"
                        },
                        "rethinkdb": {
```

### Expected behaviour
Silent logs after initial setup

### Actual behaviour
The mysql container keeps logging "access denied" on root login attempts

### Server-side log
<details>
  <summary>Container logs</summary>

  ```
[....] // regular mysql startup stuff
mysql_1   | 2020-06-01T11:12:02.669247Z 0 [Note] mysqld: ready for connections.
mysql_1   | Version: '5.7.30'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
mysql_1   | 2020-06-01T11:12:05.346102Z 2 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1   | 2020-06-01T11:12:09.463147Z 3 [Note] Access denied for user 'root'@'localhost' (using password: NO)
tinode_1  | 2020/06/01 11:12:12 Database mysql 111
tinode_1  | 2020/06/01 11:12:12 Database not found. Creating.
mysql_1   | 2020-06-01T11:12:13.586998Z 6 [Note] Access denied for user 'root'@'localhost' (using password: NO)
tinode_1  | 2020/06/01 11:12:14 Database initialized
tinode_1  | 2020/06/01 11:12:14 Generating users...
tinode_1  | 2020/06/01 11:12:16 Generating group topics...
tinode_1  | 2020/06/01 11:12:16 Generating P2P subscriptions...
tinode_1  | 2020/06/01 11:12:16 Generating group subscriptions...
tinode_1  | 2020/06/01 11:12:16 Inserting messages...
mysql_1   | 2020-06-01T11:12:17.743814Z 7 [Note] Access denied for user 'root'@'localhost' (using password: NO)
tinode_1  | 2020/06/01 11:12:21 Inserting forms as  tino dkiK7JyX-fM
mysql_1   | 2020-06-01T11:12:21.891016Z 8 [Note] Access denied for user 'root'@'localhost' (using password: NO)
tinode_1  | 2020/06/01 11:12:22 All done.
mysql_1   | 2020-06-01T11:12:22.193397Z 5 [Note] Aborted connection 5 to db: 'tinode' user: 'tinode' host: '172.22.0.3' (Got an error reading communication packets)
mysql_1   | 2020-06-01T11:12:26.087594Z 10 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1   | 2020-06-01T11:12:30.215332Z 11 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1   | 2020-06-01T11:12:34.333732Z 12 [Note] Access denied for user 'root'@'localhost' (using password: NO)
[...] // this goes on forever
  ```
</details>

### Client-side log
N/A
